### ISSUE TITLE
run / install not possible on Debian Sid

### ISSUE THREAD

**Issue by Micha-Btz** [vinsce/gneelight#1]
Hi there,

I would test your software, but I can get it to work.
run

> sysiphus ~/source/gneelight [master|✚ 1 …3] $ python3 src/GneelightApp.py
> 
> (Gneelight:5490): GLib-GIO-ERROR **: 18:02:09.637: Settings schema 'me.vinsce.gneelight' is not installed
> Trace/Breakpoint ausgelöst

flatpack

> sysiphus:~/source/downloads$ flatpak install --user gneelight.flatpak
> 
> Note that the directories 
> 
> '/var/lib/flatpak/exports/share'
> '/home/mdomann/.local/share/flatpak/exports/share'
> 
> are not in the search path set by the XDG_DATA_DIRS environment variable, so
> applications installed by Flatpak may not appear on your desktop until the
> session is restarted.
> 
> Fehler: The application me.vinsce.Gneelight/x86_64/master requires the runtime org.gnome.Platform/x86_64/master which was not found

I would run it without flatpack, just from source. Can you give me some advice how to use it?

Thanks Micha

**Comment by vinsce** [comment]
Hi @Micha-Btz , sorry for the late reply.

Your execution is missing the setting schema, as the error message says.

You have to copy the provided schema in the system and then compile the schema with the following commands:
```
sudo cp res/me.vinsce.Gneelight.gschema.xml /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
```
At this point you can run the app:
`python3 src/GneelightApp.py`

Please tell me if it solved your issue so I can update the README

**Comment by Micha-Btz** [comment]
thanks, worked.
