### ISSUE TITLE
Can't run code from source

### ISSUE THREAD

**Issue by Kreuger** [vinsce/gneelight#8]
Hey I downloaded the source but every time I try to run the app that way, it gives me the following error.

> ~/Programming/gneelight-master$ python3 src/GneelightApp.py
Traceback (most recent call last):
  File "/home/robbie/Programming/gneelight-master/src/GneelightApp.py", line 7, in <module>
    from MainWindow import MainWindow
  File "/home/robbie/Programming/gneelight-master/src/MainWindow.py", line 7, in <module>
    gi.require_version('AppIndicator3', '0.1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available

**Comment by tapionx** [comment]
same error for me, using`Ubuntu 21.10`

**Comment by vinsce** [comment]
Hi all,
you should be able to solve it by installing the `AppIndicator` library in Ubuntu with:

`sudo apt install gir1.2-appindicator3-0.1`

See also #3

**Comment by tapionx** [comment]
It works now! @vinsce maybe you can add this to the documentation too

**Comment by vinsce** [comment]
Glad it works now! I'll add it to the documentation

**Comment by Kreuger** [comment]
New error for me.

```
robbie@robbie-aspire7750:~/Programming/gneelight-master$ python3 src/GneelightApp.py
Traceback (most recent call last):
  File "/home/robbie/Programming/gneelight-master/src/GneelightApp.py", line 7, in <module>
    from MainWindow import MainWindow
  File "/home/robbie/Programming/gneelight-master/src/MainWindow.py", line 9, in <module>
    from BulbWrapper import BulbWrapper, ColorModes, Effect
  File "/home/robbie/Programming/gneelight-master/src/BulbWrapper.py", line 4, in <module>
    from yeelight import Bulb, discover_bulbs
ModuleNotFoundError: No module named 'yeelight'
```

**Comment by vinsce** [comment]
Hi @Kreuger , you can install the `yeelight` python package and try again:

```bash
pip install yeelight
```

I have updated the [README](https://github.com/vinsce/gneelight/blob/fa7b9e4c85b3bcdd2f48dd321b5ab17284715b58/README.MD#install-from-source) with these details.

**Comment by Kreuger** [comment]
I have it installed but I dont see why thats necessary to run the source. Doesnt that defeat the purpose?

**Comment by vinsce** [comment]
The `yeelight` python package is the underlying library used by Gneelight to communicate with lights and it is an external project (https://github.com/skorokithakis/python-yeelight).

The yeelight library is not the same as the Gneelight application, if I understand your question correctly, but it is required in order to run the application.

**Comment by Kreuger** [comment]
Sorry yes. I misunderstood what you meant. I thought you were asking me to install Gneelight. Haha.

Edit: Yet another error has come up.

> robbie@robbie-aspire7750:~/Programming/gneelight-master$ python3 src/GneelightApp.py
 Traceback (most recent call last):
 File "/home/robbie/Programming/gneelight-master/src/GneelightApp.py", line 63, in do_activate
     self.window = MainWindow(application=self, title=APP_NAME)
   File "/home/robbie/Programming/gneelight-master/src/MainWindow.py", line 48, in __init__
     self.indicator = self.init_indicator()
  File "/home/robbie/Programming/gneelight-master/src/MainWindow.py", line 241, in init_indicator
     indicator = AppIndicator3.Indicator.new(APP_NAME, APP_ICON, AppIndicator3.IndicatorCategory.APPLICATION_STATUS)
   NameError: name 'AppIndicator3' is not defined

Also, it just hung after that. I had to use ctrl+c to close the app which also threw up an error (warning?):

> ^CTraceback (most recent call last):
  File "/home/robbie/Programming/gneelight-master/src/GneelightApp.py", line 87, in <module>
    exit_status = app.run(sys.argv)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 43, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "/usr/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/usr/lib/python3/dist-packages/gi/_ossighelper.py", line 237, in register_sigint_fallback
    signal.default_int_handler(signal.SIGINT, None)
KeyboardInterrupt

**Comment by vinsce** [comment]
You need one last dependency that is the `PyGObject` python library for GNOME.

In the repository root you can find the file [`requirements.txt`](https://github.com/vinsce/gneelight/blob/master/requirements.txt) file which lists all the python dependencies that must be installed in order to run from source code.
You can install them all at once with:
```bash
pip install -r requirements.txt
```
or you can install individual dependencies:
```bash
pip install yeelight
pip install PyGObject
```

Note that you may need to install other system-side libraries depending on your OS. For example to install PyGObject in Ubuntu you need to install also `python3-dev` and `libgirepository1.0-dev` using apt.

The flatpak solution is easier :)

**Comment by Kreuger** [comment]
To me its easier ti have deb packages and let apt handle it, but I digress. I want to poke around the code, try to play with things and learn.
