### ISSUE TITLE
can't install flatpak package on Ubuntu 20.10

### ISSUE THREAD

**Issue by tapionx** [vinsce/gneelight#9]
```
flatpak install --user gneelight.flatpak

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/XXXX/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

error: The application me.vinsce.Gneelight/x86_64/master requires the runtime org.gnome.Platform/x86_64/3.38 which was not found
```

**Comment by vinsce** [comment]
Hi @tapionx ,
Can you try to manually install the required Gnome runtime?

```
flatpak --user remote-add --from flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak --user install flathub org.gnome.Platform//3.38
```

**Comment by tapionx** [comment]
it works now @vinsce thanks! Maybe add this in the documentation?

**Comment by vinsce** [comment]
Glad it works now! I'll add it to the documentation

**Comment by Grief** [comment]
```
> flatpak install --user gneelight.flatpak                                                                                                     [code: 0, time: 0.000s]
error: The application me.vinsce.Gneelight/x86_64/master requires the runtime org.gnome.Platform/x86_64/40 which was not found                            
> flatpak --user install flathub org.gnome.Platform//40
Looking for matches?
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
```

**Comment by vinsce** [comment]
> ```
> > flatpak install --user gneelight.flatpak                                                                                                     [code: 0, time: 0.000s]
> error: The application me.vinsce.Gneelight/x86_64/master requires the runtime org.gnome.Platform/x86_64/40 which was not found                            
> > flatpak --user install flathub org.gnome.Platform//40
> Looking for matches?
> Info: org.gnome.Platform//40 is end-of-life, with reason:
>    The GNOME 40 runtime is no longer supported as of March 21, 2022. Please ask your application developer to migrate to a supported platform.
> ```

Hi @Grief , the new [release 1.0.6](https://github.com/vinsce/gneelight/releases/tag/v.1.0.6) is based on `org.gnome.Platform/42`
